# Generated by Django 4.1 on 2022-09-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0006_customer_user_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
